apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:                        #A
- ../../base

patchesStrategicMerge:
- guestbook-patch.yaml        #B

images:                       #C
- name: acme.com/guestbook
  newTag: v1.0.0
